#pragma checksum "..\..\..\Properties\SpreadTraderWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D95479415FF6630444360276545687036CFF935B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.WpfPropertyGrid;
using System.Windows.Controls.WpfPropertyGrid.Controls;
using System.Windows.Controls.WpfPropertyGrid.Design;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Zweistein;


namespace Zweistein {
    
    
    /// <summary>
    /// SpreadTraderWindow
    /// </summary>
    public partial class SpreadTraderWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 11 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGoLong;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnReverse;
        
        #line default
        #line hidden
        
        
        #line 13 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnGoShort;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 15 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnPosition;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnValue;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button unrealizedPNL;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RichTextBox realizedPNL;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid opentickets;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtTicket;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddTicket;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\Properties\SpreadTraderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WpfPropertyGrid.PropertyGrid Parameters;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/SpreadTraderWindow;component/properties/spreadtraderwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Properties\SpreadTraderWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 9 "..\..\..\Properties\SpreadTraderWindow.xaml"
            ((Zweistein.SpreadTraderWindow)(target)).LocationChanged += new System.EventHandler(this.Window_LocationChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnGoLong = ((System.Windows.Controls.Button)(target));
            return;
            case 3:
            this.btnReverse = ((System.Windows.Controls.Button)(target));
            return;
            case 4:
            this.btnGoShort = ((System.Windows.Controls.Button)(target));
            return;
            case 5:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            return;
            case 6:
            this.btnPosition = ((System.Windows.Controls.Button)(target));
            return;
            case 7:
            this.btnValue = ((System.Windows.Controls.Button)(target));
            return;
            case 8:
            this.unrealizedPNL = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.realizedPNL = ((System.Windows.Controls.RichTextBox)(target));
            return;
            case 10:
            this.opentickets = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 12:
            this.txtTicket = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.btnAddTicket = ((System.Windows.Controls.Button)(target));
            
            #line 43 "..\..\..\Properties\SpreadTraderWindow.xaml"
            this.btnAddTicket.Click += new System.Windows.RoutedEventHandler(this.btnAddTicket_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.Parameters = ((System.Windows.Controls.WpfPropertyGrid.PropertyGrid)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 11:
            
            #line 35 "..\..\..\Properties\SpreadTraderWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.btnDelTicket_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

